### ISSUE TITLE
No such file or directory: 'out/image (17).jpg'

### ISSUE THREAD

**Issue by AreYouLoco** [creotiv/ReCaptcha-resolver#1]
Traceback (most recent call last):
  File "test_preprocess.py", line 5, in <module>
    from preprocess import intel_crop,normalize_sin,getCenterLine,split_words,find_angles,find_breaks
  File "/home/orest/DEV/ReCaptcha-resolver/preprocess.py", line 1, in <module>
    import cv
ImportError: No module named cv

So then I installed python-opencv

Pure just cloned repo:

$ python test_preprocess.py captchas out
Traceback (most recent call last):
  File "test_preprocess.py", line 23, in <module>
    img.save(patho+imp,'JPEG')
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 1433, in save
    fp = **builtin**.open(fp, "wb")
IOError: [Errno 2] No such file or directory: 'out/image (17).jpg'

...

**Comment by creotiv** [comment]
This my personal library for wor with recaptcha it's too old and not
maintained. So i can't give you an answer. Sorry.

Kindly yours,
Andrey Nikishaev

Essenly http://essenly.com - книги в кратком изложении.
groovyCV http://groovycv.com - создание стильных резюме

LinkedIn      http://ua.linkedin.com/in/creotiv
GitHub        http://github.com/creotiv
Skype         creotiv.in.ua
Mobile        +380632410666
